
model:
    model_id: "stabilityai/sdxl-turbo"
    cache_dir: /home/group-3/hf_cache
    model_type: 'sdxl'  # ['sd','sdxl']
conditional: True
mixed_precision: [2,4,8]
calib_data:
    path: "/home/group-3/tests_L/MixDQ/logs/calib_dataset/sdxl_turbo_calib.pt"
    n_steps: 1
    batch_size: 8  # used for quant param initialization
    n_samples: 32
    scale_type: "fix"
    scale_value: 0.
quant:
    weight:
        optimization:
        quantizer:
            n_bits: 8
            sym: True
            channel_wise: True
            scale_method: 'min_max'
            round_mode: 'nearest'
    activation:
        optimization:
        quantizer:
            n_bits: 8
            channel_wise: False
            scale_method: 'min_max'
            round_mode: 'nearest_ste'
            running_stat: True
            bos_aware: True
            softmax: 
    grad_checkpoint: False
resume_with_w_quantized:
    path: None





